test:
  - src/GraphQLParser.Tests/**/*
  - src/GraphQLParser.ApiTests/**/*.cs

CI:
  - .github/workflows/**/*
  - .github/dependabot.yml
  - .github/labeler.yml
  - .github/codecov.yml

code style:
  - .editorconfig

documentation:
  - README.md

performance:
  - src/GraphQLParser.Benchmarks/**/*
