test:
  - src/GraphQLParser.ApiTests/**/*
  - src/GraphQLParser.Tests/**/*

CI:
  - .github/workflows/**/*
  - .github/dependabot.yml

code style:
  - .editorconfig

documentation:
  - README.md

performance:
  - src/GraphQLParser.Benchmarks/**/*
